export const projects = [
  {
    slug: "dastak",
    title: "Maryam Ki Dastak",
    subtitle: "Doorstep government services for 110M+ citizens across Punjab",
    stat: "2.1M",
    statLabel: "citizens served",
    year: "2023",
    image: "/images/dastak/dastak_homepage_card.jpg",
    role: "Principal UX/UI Designer",
    client: "Government of Punjab",
    platforms: "Web Portal, Mobile App, Facilitator App, CRM",
    team: "20+ people",
  },
  {
    slug: "city-watch",
    title: "City Watch",
    subtitle: "Real-time surveillance and response platform for public safety",
    stat: "8,000+",
    statLabel: "cameras integrated",
    year: "2022",
    image: null,
    role: "Principal UX/UI Designer",
    client: "Punjab Safe City Authority",
    platforms: "Web Application",
    team: "5–10 people",
  },
  {
    slug: "punjab-jobs",
    title: "Punjab Jobs",
    subtitle: "Redesigning Punjab's employment platform for government job seekers",
    stat: "500K+",
    statLabel: "registered users",
    year: "2024",
    image: null,
    role: "Program Manager — Design",
    client: "PITB",
    platforms: "Web Portal, Recruiter Module, Mobile App",
    team: "2–5 people",
  },
  {
    slug: "ess",
    title: "Employee Self Service",
    subtitle: "Workplace community platform for 3,500+ PITB employees",
    stat: "98%",
    statLabel: "daily adoption",
    year: "2022",
    image: null,
    role: "Principal UX/UI Designer",
    client: "PITB (internal)",
    platforms: "Native Mobile App",
    team: "5–10 people",
  },
  {
    slug: "pitb-official",
    title: "PITB Official",
    subtitle: "Flagship web portal for Punjab's technology authority",
    stat: "13",
    statLabel: "screens, 30 hours",
    year: "2025",
    image: null,
    role: "Program Manager — Design",
    client: "PITB",
    platforms: "Website",
    team: "2–3 people",
  },
  {
    slug: "aqi",
    title: "Punjab AQI",
    subtitle: "Environmental monitoring platform making air quality actionable",
    stat: "36",
    statLabel: "districts monitored",
    year: "2025",
    image: null,
    role: "Program Manager — Design",
    client: "Environmental Protection Department",
    platforms: "Web Dashboard",
    team: "2–5 people",
  },
  {
    slug: "ebiz",
    title: "eBiz Punjab",
    subtitle: "One portal for business registration, licenses, and permits across multiple departments",
    stat: "100K+",
    statLabel: "business registrations",
    year: "2024–2025",
    image: null,
    role: "Program Manager — Design",
    client: "Government of Punjab",
    platforms: "Web Portal, Admin CRM",
    team: "5–10 people",
  },
];
